# Generated by Django 5.2.15 on 2026-06-16 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('content', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingsession',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_sessions', to='users.child'),
        ),
        migrations.AddField(
            model_name='viewingsession',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_sessions', to='content.story'),
        ),
        migrations.AddIndex(
            model_name='viewingsession',
            index=models.Index(fields=['child', '-started_at'], name='viewing_ses_child_i_32526a_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingsession',
            index=models.Index(fields=['story'], name='viewing_ses_story_i_ca6f68_idx'),
        ),
    ]
