# Generated by Django 5.2.15 on 2026-06-16 07:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_sub', models.TextField(blank=True, default=None, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.TextField(blank=True, default='')),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('plan', models.CharField(default='free', max_length=20)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('content_admin', 'Content Admin'), ('translator', 'Translator'), ('analyst', 'Analyst')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_users',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField()),
                ('birth_month', models.IntegerField()),
                ('language', models.CharField(max_length=10)),
                ('last_seen_age_group', models.CharField(blank=True, choices=[('12_18m', '12–18 months'), ('18_30m', '18–30 months'), ('30_42m', '30–42 months'), ('42_60m', '42–60 months'), ('60m_plus', '60+ months (graduated)')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'children',
                'indexes': [models.Index(fields=['user'], name='children_user_id_461969_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('birth_year__gte', 2019), ('birth_year__lte', 2030)), name='children_birth_year_range'), models.CheckConstraint(condition=models.Q(('birth_month__gte', 1), ('birth_month__lte', 12)), name='children_birth_month_range')],
            },
        ),
    ]
