# Generated by Django 5.2.15 on 2026-06-16 07:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('icon_url', models.TextField(blank=True, default='')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=50)),
                ('is_rtl', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('age_group', models.CharField(choices=[('12_18m', '12–18 months'), ('18_30m', '18–30 months'), ('30_42m', '30–42 months'), ('42_60m', '42–60 months')], max_length=20)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('cover_url', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='content.category')),
            ],
            options={
                'db_table': 'stories',
            },
        ),
        migrations.CreateModel(
            name='StoryTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('manifest_url', models.TextField()),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.CASCADE, to='content.language')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.story')),
            ],
            options={
                'db_table': 'story_translations',
            },
        ),
        migrations.CreateModel(
            name='UIString',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.CASCADE, to='content.language')),
            ],
            options={
                'db_table': 'ui_strings',
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.category')),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.CASCADE, to='content.language')),
            ],
            options={
                'db_table': 'category_translations',
                'unique_together': {('category', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['status', 'age_group'], name='stories_status_b90ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['category', 'status'], name='stories_categor_56f0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='storytranslation',
            index=models.Index(fields=['language', 'story'], name='story_trans_languag_6417f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storytranslation',
            unique_together={('story', 'language')},
        ),
        migrations.AddIndex(
            model_name='uistring',
            index=models.Index(fields=['language'], name='ui_strings_languag_0af0d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uistring',
            unique_together={('key', 'language')},
        ),
    ]
