# Generated by Django 5.2.15 on 2026-06-20 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='segmentasset',
            name='unique_segment_asset_language',
        ),
        migrations.RemoveConstraint(
            model_name='storysegment',
            name='unique_draft_segment_index',
        ),
        migrations.RemoveIndex(
            model_name='segmentasset',
            name='idx_segment_asset_language',
        ),
        migrations.RenameIndex(
            model_name='generationjob',
            new_name='generation__draft_i_7f7e53_idx',
            old_name='idx_job_draft_status',
        ),
        migrations.RenameIndex(
            model_name='generationjob',
            new_name='generation__draft_i_8ce1d7_idx',
            old_name='idx_job_draft_type',
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='segmentasset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='segmentasset',
            name='language',
            field=models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.language'),
        ),
        migrations.AlterField(
            model_name='storydraft',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storysegment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='segmentasset',
            unique_together={('segment', 'asset_type', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='storysegment',
            unique_together={('draft', 'index')},
        ),
    ]
