# Generated by Django 5.2.15 on 2026-06-20 20:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_remove_segmentasset_unique_segment_asset_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storydraft',
            name='age_group',
        ),
        migrations.AddField(
            model_name='storydraft',
            name='age_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('12_18m', '12–18 months'), ('18_30m', '18–30 months'), ('30_42m', '30–42 months'), ('42_60m', '42–60 months')], max_length=20), default=list, size=None),
        ),
    ]
